VOCAB = [
    # Shops
    ("baker's", "panadería"),
    ("florist's", "floristería"),
    ("barber's", "barbería"),
    ("garden centre", "centro de jardinería"),
    ("butcher's", "carnicería"),
    ("greengrocer's", "frutería"),
    ("car showroom", "concesionario"),
    ("hairdresser's", "peluquería"),
    ("chain store", "tienda de cadena"),
    ("jeweller's", "joyería"),
    ("chemist's", "farmacia"),
    ("launderette", "lavandería automática"),
    ("deli", "tienda delicatessen (embutidos... quesos)"),
    ("market stall", "puesto de mercado"),
    ("DIY store", "tienda de bricolaje"),
    ("newsagent's", "quiosco"),
    ("dry-cleaner's", "tintorería"),
    ("off-licence", "tienda de alcohol"),
    ("estate agent's", "inmobiliaria"),
    ("stationer's", "papelería"),
    ("fishmonger's", "pescadería"),
    ("travel agent's", "agencia de viajes"),

    # TV & Media
    ("advert", "anuncio"),
    ("cartoon", "dibujos animados"),
    ("animation", "animación"),
    ("chat show", "programa de entrevistas"),
    ("cookery programme", "programa de cocina"),
    ("current affairs programme", "programa de actualidad"),
    ("documentary", "documental"),
    ("crime drama", "drama policíaco"),
    ("live sport", "deporte en directo"),
    ("period drama", "drama de época"),
    ("quiz show", "concurso"),
    ("reality show", "reality show"),
    ("the news", "las noticias"),
    ("the weather forecast", "el parte meteorológico"),

    # University
    ("campus", "campus universitario"),
    ("dissertation", "disertación"),
    ("faculties", "facultades"),
    ("halls of residence", "residencias universitarias"),
    ("lectures", "clases universitarias"),
    ("postgraduates", "estudiantes de posgrado"),
    ("professors", "profesores"),
    ("seminars", "seminarios"),
    ("thesis", "tesis"),
    ("tutor", "tutor"),
    ("undergraduates", "estudiantes de grado"),
    ("webinars", "webinars"),

    # Work
    ("CV", "currículum"),
    ("experience", "experiencia"),
    ("intern", "becario"),
    ("interview", "entrevista"),
    ("job offer", "oferta de trabajo"),
    ("permit", "permiso"),
    ("qualifications", "cualificaciones"),
    ("skills", "habilidades"),
    ("vacancy", "vacante"),

    # Containers & packaging
    ("bottle", "botella"),
    ("can", "lata"),
    ("cardboard box", "caja de cartón"),
    ("carton", "brik"),
    ("jar", "tarro"),
    ("lid", "tapa"),
    ("cap", "tapón"),
    ("packet", "paquete"),
    ("plastic bag", "bolsa de plástico"),
    ("pot", "bote yogur"),
    ("pouch", "bolsa pequeña comida"),
    ("sell-by date", "fecha de caducidad"),
    ("tin", "lata"),
    ("polystyrene tray", "bandeja de poliestireno"),
    ("tub", "tarrina (de helado por ejemplo)"),
    ("wrapper", "envoltorio"),

    # Describing photos / position
    ("behind", "detrás"),
    ("in the background", "en el fondo"),
    ("in the bottom right-hand corner", "en la esquina inferior derecha"),
    ("in the centre", "en el centro"),
    ("in the distance", "a lo lejos"),
    ("in the foreground", "en primer plano"),
    ("in front of", "delante de"),
    ("in the top left-hand corner", "en la esquina superior izquierda"),
    ("on top of", "encima de"),
    ("opposite", "enfrente"),

    # Waste & recycling
    ("bin", "cubo de basura"),
    ("bin bag", "bolsa de basura"),
    ("landfill site", "vertedero"),
    ("refuse collector", "basurero"),
    ("rubbish", "basura"),
    ("waste", "residuos"),
    ("waste-paper basket", "papelera"),

    # Phrasal verbs
    ("give away", "regalar"),
    ("take away", "tirar / quitar"),
    ("take out", "sacar"),
    ("throw away", "tirar"),
]